stages:
  - test

variables:
  DB_CONNECTION: mariadb
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: test_evaluation_panel
  DB_USERNAME: newuser
  DB_PASSWORD: mypassword
  APP_ENV: testing
  APP_DEBUG: true

test_job:
  stage: test
  script:
    - echo "Starting CI pipeline..."
    - echo "$(date)" > time.txt

    - apt-get update -yqq
    - apt-get install -yqq php php-cli php-mbstring php-xml php-bcmath php-zip php-mysql unzip mariadb-server mariadb-client

    - service mariadb start
    - mariadb -e "CREATE DATABASE IF NOT EXISTS test_evaluation_panel CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

    - unzip -o vendor.zip -d .
    - chmod 775 -R ./vendor

    - cp .env.testing .env

    - php artisan key:generate

    - php artisan migrate --env=testing --force

    - ./vendor/bin/phpunit --log-junit=tests/reports/junit.xml

    - echo "Tests completed at $(date)" >> time.txt

  artifacts:
    when: always
    paths:
      - test_output.txt
      - tests/reports/junit.xml
      - time.txt
    expire_in: 1 week
