FROM php:8.3-fpm

RUN apt-get update -yqq && \
    apt-get install -yqq git unzip zip libzip-dev mariadb-client libpng-dev libonig-dev libxml2-dev && \
    docker-php-ext-install pdo_mysql zip mbstring
